version: '3'
services:
  authentification:
    image: authentification
    build:
      context: .
      dockerfile: ./apps/authentification/Dockerfile
      target: development
    restart: always
    command: npm run authentification
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      - 'rabbitmq'

  blog:
    image: blog
    build:
      context: .
      dockerfile: ./apps/blog/Dockerfile
      target: development
    restart: always
    command: npm run blog
    env_file: .env
    ports:
      - '4001:4001'
    depends_on:
      - 'rabbitmq'

  managementclub:
    image: managementclub
    build:
      context: .
      dockerfile: ./apps/managementclub/Dockerfile
      target: development
    restart: always
    command: npm run managementclub
    env_file: .env
    ports:
      - '4002:4002'
    depends_on:
      - 'rabbitmq'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
